spring.application.name=Zorvyn_Project
spring.datasource.url=${url}
spring.datasource.username=${username}
spring.datasource.password=${pass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JwtKey}